#!/bin/bash -e

TOOL=Ninja
CMD="ninja -j4 -C"
if [ ! -x /usr/bin/ninja ]; then
  TOOL="Unix Makefiles"
  CMD="make -j4 -C"
fi

echo "cmake -S . -B .build-debug -G $TOOL"
cmake -S . -B .build-debug -G "$TOOL"

echo

echo "$CMD .build-debug"
$CMD .build-debug

echo

go test ./...
#echo .build-debug/all_tests
#.build-debug/all_tests