#!/bin/bash -e
cd "$(dirname "$0")"
export GOBIN="$PWD/bin"

TOOL=Ninja
CMD="ninja -j4 -C"
if [ ! -x /usr/bin/ninja ]; then
  TOOL="Unix Makefiles"
  CMD="make -j4 -C"
fi

echo "cmake -S . -B .build-debug -G $TOOL"
cmake -S . -B .build-debug -G "$TOOL"

echo

echo "$CMD .build-debug"
$CMD .build-debug

echo "--"
go test ./...
go install ./cmd/...

echo
echo "-- cpp_main"
.build-debug/cpp_main

echo
echo "-- swig-go-cpp C++"
.build-debug/cmd/swig-go-cpp

echo
echo "-- swig-go-cpp Go"
bin/swig-go-cpp

